name: Build and Test All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENABLE_LOGGING: true # Enable/disable logging in CI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        exercise: [01, 02]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Example
      - name: Build example (optional)
        run: |
          if find examples -name "${{ matrix.exercise }}_*_example.c" | grep -q .; then
            make EXERCISE=${{ matrix.exercise }} run_example
          else
            echo "Example not found. Skipping."
          fi

      # Manual test
      - name: Run manual test (optional)
        run: |
          if find tests/manual -name "${{ matrix.exercise }}_*_manual.c" | grep -q .; then
            make EXERCISE=${{ matrix.exercise }} run_manual_test
          else
            echo "Manual test not found. Skipping."
          fi

      # Unity test
      - name: Run Unity test (optional)
        run: |
          if find tests/unity -name "${{ matrix.exercise }}_*_unity.c" | grep -q .; then
            make EXERCISE=${{ matrix.exercise }} run_unity_test
          else
            echo "Unity test not found. Skipping."
          fi

      - name: Check include paths
        run: make EXERCISE=${{ matrix.exercise }} check_includes || echo "Include check skipped"
