name: Build and Test All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build example
        run: make EXERCISE=01 run_example

      - name: Run manual test
        run: make EXERCISE=01 run_manual_test

      - name: Run Unity test
        run: make EXERCISE=01 run_unity_test
