name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build

      # Optional: Run tests (we'll add CTest support soon)
      - name: Run Unity tests (if any)
        run: |
          echo "=== Executables ==="
          find build/bin -type f -executable
          echo "=== Running tests ==="
          for f in build/bin/unity_*; do
            echo "Running $f"
            $f
          done
