name: Build and Test All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENABLE_LOGGING: true # Enable/disable logging in CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build example
        run: |
          if [ "$ENABLE_LOGGING" = "true" ]; then
            make EXERCISE=01 LOG=1 run_example
          else
            make EXERCISE=01 run_example
          fi

      - name: Run manual test
        run: |
          if [ "$ENABLE_LOGGING" = "true" ]; then
            make EXERCISE=01 LOG=1 run_manual_test
          else
            make EXERCISE=01 run_manual_test
          fi

      - name: Run Unity test
        run: |
          if [ "$ENABLE_LOGGING" = "true" ]; then
            make EXERCISE=01 LOG=1 run_unity_test
          else
            make EXERCISE=01 run_unity_test
          fi